services:
  t2s-db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    networks:
      - app-network

  t2s-django:
    build:
      context: ./t2s_backend
      dockerfile: Dockerfile
    container_name: t2s-django
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput --clear &&
             python manage.py initadmin &&
             uvicorn t2s_backend.asgi:application --host 0.0.0.0 --port 8000 --workers 1"
    working_dir: /app
    volumes:
      - static_volume:/app/static
      - ./incity.db:/app/incity.db:ro
    expose:
      - "8000"
    env_file: .env
    depends_on:
      t2s-db:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    networks:
      - app-network

  celery:
    container_name: celery_worker
    build:
      context: ./t2s_backend
      dockerfile: Dockerfile
    command: >
      celery -A t2s_backend worker --loglevel=INFO
    volumes:
      - static_volume:/app/static
      - ./incity.db:/app/incity.db:ro
    env_file: .env
    depends_on:
      t2s-django:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    networks:
      - app-network

  celery-beat:
    build:
      context: ./t2s_backend
      dockerfile: Dockerfile
    container_name: celery-beat
    command: celery -A t2s_backend beat --loglevel=info
    working_dir: /app
    volumes:
      - static_volume:/app/static
      - ./incity.db:/app/incity.db:ro
    env_file:
      - .env
    depends_on:
      t2s-django:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7-alpine
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app-network

  t2s-frontend:
    build:
      context: ./t2s_frontend
      dockerfile: Dockerfile
    container_name: t2s-frontend
    expose:
      - "3000"
    depends_on:
      - t2s-django
    restart: always
    networks:
      - app-network

  t2s-nginx:
    image: nginx:1.27-alpine
    container_name: t2s-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
    depends_on:
      - t2s-django
      - t2s-frontend
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  redis_data:

networks:
  app-network:
    driver: bridge