# Generated by Django 6.0.4 on 2026-04-23 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_message_metadata_message_description_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_lookup_id", models.PositiveBigIntegerField(verbose_name="ID сообщения для поиска по message_id")),
                ("scheduled_at", models.DateTimeField(verbose_name="Дата и время отправки")),
                ("comment", models.TextField(blank=True, default="", verbose_name="Комментарий")),
                (
                    "repeat",
                    models.CharField(
                        choices=[
                            ("none", "Без повтора"),
                            ("day", "Каждый день"),
                            ("week", "Каждую неделю"),
                            ("month", "Каждый месяц"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Повторение",
                    ),
                ),
                ("periodic_task_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Имя periodic task")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="email_mailings",
                        to="core.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email-рассылка",
                "verbose_name_plural": "Email-рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailMailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("unsubscribe_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Токен отписки")),
                ("is_unsubscribed", models.BooleanField(default=False, verbose_name="Отписан")),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата отписки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="recipients",
                        to="users.emailmailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ["email"],
            },
        ),
        migrations.AddConstraint(
            model_name="emailmailingrecipient",
            constraint=models.UniqueConstraint(fields=("mailing", "email"), name="unique_email_per_mailing"),
        ),
    ]
