# Generated by Django 6.0.4 on 2026-04-22 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_message_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='metadata',
        ),
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_message_id', to='core.message', verbose_name='Ответ на сообщение'),
        ),
    ]
