# Generated by Django 6.0.4 on 2026-04-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_message_metadata_message_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite')], max_length=32, verbose_name='Тип БД')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Логин')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль')),
                ('database_name', models.CharField(blank=True, default='', max_length=255, verbose_name='База данных')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='Хост')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт')),
                ('sqlite_file', models.FileField(blank=True, null=True, upload_to='db_files/sqlite/', verbose_name='Файл SQLite')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активное подключение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Подключение к БД',
                'verbose_name_plural': 'Подключения к БД',
                'ordering': ['-updated_at'],
            },
        ),
    ]
